import "../styles/global.css";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Адвокатське бюро Тетяни Савченко",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ua">
      <body className={inter.className}>
        <Navbar />
        <div className="container mx-auto mt-[40px]">{children}</div>
      </body>
    </html>
  );
}
